apply patches to fix aarch64 with OpenGL ES
Adapt patches from ARM łOpenSuse to fix aarch64 build with OpenGL ES. Needed because current aarch64 in Cooker switch from desktop OpenGL to OpenGL ES and this cause issues on some packages like VTK ot Shotcut.

Errors:
error: unknown type name 'QOpenGLFunctions_3_2_Core'; did you mean 'QOpenGLFunctionsPrivate'?
DEBUG util.py:623:      QOpenGLFunctions_3_2_Core* f = this->Context->versionFunctions<QOpenGLFunctions_3_2_Core>();

error: no member named 'glBindFramebuffer' in 'QOpenGLFunctionsPrivate'
DEBUG util.py:623:      f->glBindFramebuffer(GL_DRAW_FRAMEBUFFER, targetId);
DEBUG util.py:623:      ~  ^
DEBUG util.py:623:  ../GUISupport/Qt/QVTKRenderWindowAdapter.cxx:344:8: error: no member named 'glDrawBuffer' in 'QOpenGLFunctionsPrivate'
DEBUG util.py:623:      f->glDrawBuffer(targetAttachment);